version: '2'

services:
  memcached1:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11211:11211'
  memcached2:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11212:11211'
  memcached3:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11213:11211'
  memcached:
    image: tianon/true
    depends_on: 
    - memcached1
    - memcached2
    - memcached3
  hashring:
    build:
      dockerfile: Dockerfile.python2
    working_dir: '/scripts'
    environment:
      - NUMBER_ITEMS_TO_SEED=500
    entrypoint: 'python hash_ring_test.py'
    volumes:
      - '.:/scripts'
  pylibmc:
    build:
      dockerfile: Dockerfile.python3
    working_dir: '/scripts'
    entrypoint: 'python pylibmc_test.py'
    volumes:
      - '.:/scripts'
  seed_with_ingestion:
    build:
      dockerfile: Dockerfile.python3
    working_dir: '/scripts'
    entrypoint: 'python seed_with_ingestion.py'
    environment:
      - NUMBER_ITEMS_TO_SEED=500
    volumes: 
      - '.:/scripts'
  seed_with_hashring:
    build:
      dockerfile: Dockerfile.python2
    working_dir: '/scripts'
    entrypoint: 'python seed_with_hashring.py'
    environment:
      - NUMBER_ITEMS_TO_SEED=500
    volumes: 
      - '.:/scripts'
  seed_with_moxmemcache:
    build:
      dockerfile: Dockerfile.python2
    working_dir: '/scripts'
    entrypoint: 'python seed_with_moxmemcache.py'
    environment:
      - NUMBER_ITEMS_TO_SEED=500
    volumes: 
      - '.:/scripts'
  
  moxapi: 
    image: moxapi:dev
    entrypoint: node /app/scripts/seed_memcached.js
    environment:
      - NUMBER_ITEMS_TO_SEED=500
    volumes: 
      - './added_data:/app/added_data'