version: '2'

services:
  memcached1:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11211:11211'
  memcached2:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11212:11211'
  memcached3:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11213:11211'
  memcached:
    image: tianon/true
    depends_on: 
    - memcached1
    - memcached2
    - memcached3
  hashring:
    build:
      dockerfile: Dockerfile.python2
    working_dir: '/scripts'
    environment:
      - NUMBER_ITEMS_TO_SEED=500
    entrypoint: 'python hash_ring_test.py'
    volumes:
      - '.:/scripts'
  mox_memcache_test:
    build:
      dockerfile: Dockerfile.python2
    working_dir: '/scripts'
    entrypoint: 'python mox_memcache_test.py'
    volumes:
      - '.:/scripts'
  ingestion_memcache_test:
    build:
      dockerfile: Dockerfile.python3
    working_dir: '/scripts'
    entrypoint: 'python ingestion_memcache_test.py'
    volumes:
      - '.:/scripts'
  seed_with_ingestion:
    build:
      dockerfile: Dockerfile.python3
    working_dir: '/scripts'
    entrypoint: 'python seed_with_ingestion.py'
    volumes: 
      - '.:/scripts'
  seed_with_hashring:
    build:
      dockerfile: Dockerfile.python2
    working_dir: '/scripts'
    entrypoint: 'python seed_with_hashring.py'
    volumes: 
      - '.:/scripts'
  seed_with_moxmemcache:
    build:
      dockerfile: Dockerfile.python2
    working_dir: '/scripts'
    entrypoint: 'python seed_with_moxmemcache.py'
    volumes: 
      - '.:/scripts'
  seed_with_moxapi: 
    # image: moxapi:dev  #if you build locally off of memcache-compat-test branch 
    image: us.gcr.io/rollbar-staging/moxapi:memcache-test
    entrypoint: node /app/scripts/write_to_memcached.js
    volumes: 
      - './added_data:/app/added_data'
  moxapi_memcache_test: 
    image: moxapi:dev #if you build locally off of memcache-compat-test branch
    # image: us.gcr.io/rollbar-staging/moxapi:memcache-test # moxapi:dev if you build locally off of memcache-compat-test branch
    entrypoint: node /app/scripts/fetch_from_memcached.js
    volumes: 
      - './added_data:/app/added_data'